hostname: "{{ machine }}"
---
when: os == "macos"

files:
  - source: home
    destination: ~/
    link_files: true
  - source: files/com.googlecode.iterm2.plist
    destination: ~/Library/Preferences/com.googlecode.iterm2.plist

directories:
  - ~/Screenshots/{{ machine }}

git.repo:
  - source: https://github.com/ohmyzsh/ohmyzsh.git
    destination: ~/External/.oh-my-zsh
  - source: https://github.com/folke/lazy.nvim.git
    destination: ~/.local/share/nvim/lazy/lazy.nvim

link-cleanup:
  - ~/.local/bin

packages:
  - coreutils
  - git-delta
  - node
  - bat
  - meetingbar
  - 1password/tap/1password-cli
  - awscli
  - session-manager-plugin
  - homebrew/cask/visual-studio-code
  - steam
  - homebrew/cask/iterm2
  - less
  - wget
  - woof
  - htop
  - whois
  - openssh
  - ripgrep
  - ssh-copy-id
  - rsync
  - lsof
  - nmap
  - screen
  - tmux
  - zip
  - jq
  - python-yq
  - watch
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - brew-cask-completion
  - launchctl-completion
  - netcat
  - homebrew/cask/spotify
  - homebrew/cask/adobe-acrobat-reader
  - homebrew/cask/meetingbar
  - kap
  - homebrew/cask/font-inconsolata-nerd-font
  - git
  - gh
  - hub
  - gnupg
  - cloc
  - homebrew/cask/docker
  - direnv
  - shellcheck
  - shfmt
  - fzf
  - pnpm
  - planetscale/tap/pscale
  - mysql-client
  - neovim
  - discord
  - mise
  - jdx/tap/usage
  - tree
  - zed
  - parallel
  - homebrew/cask/iina
  - mysql
  - homebrew/cask/mist
  # secureframe stuff
  - postgresql@16
  - dopplerhq/cli/doppler
  - yarn
  - python@3.10
  - redis
  - pkg-config
  - pixman
  - cairo
  - pango
  - getsentry/tools/sentry-cli
  - git-filter-repo
  - vips
  - prowler

default.programs:
  .todo: Visual Studio Code
  .txt: Visual Studio Code
  .sh: Visual Studio Code
  .md: Visual Studio Code
  .yml: Visual Studio Code
  .json: Visual Studio Code
  .js: Visual Studio Code
  .jsx: Visual Studio Code
  .ts: Visual Studio Code
  .tsx: Visual Studio Code
  .rb: Visual Studio Code
  .erb: Visual Studio Code
  .xml: Visual Studio Code
  http://: Google Chrome
  file://: Finder
  .graphql: Visual Studio Code

# macos.terminal.theme: files/mine.terminal

macos.hide:
  - ~/Music
  - ~/Public
  - ~/Movies
  - ~/Pictures

macos.show:
  - /Volumes

macos.pmset:
  all:
    standby: 1
    disksleep: 10
    hibernatemode: 0

macos.defaults:
  # % System and Menubar

  - domain: com.apple.menuextra.clock
    name: DateFormat
    value: "EEE MMM d  h:mm a"

  # TODO: confirm AppleMenuBarVisibleInFullscreen is sufficient on new machines & verify resets
  # System Preferences > Desktop & Dock > Menu Bar > Automatically hide and show the menu bar
  - domain: NSGlobalDomain
    name: AppleMenuBarVisibleInFullscreen
    value: true
    resets: SystemUIServer # / Dock?

  # dark mode
  - domain: NSGlobalDomain
    name: AppleInterfaceStyle
    value: Dark
    resets: Dock
  - domain: NSGlobalDomain
    name: AppleInterfaceStyleSwitchesAutomatically
    value: false
    resets: Dock

  # System Preferences > General > Accent color
  #  Color    AppleAquaColorVariant AppleAccentColor
  #    Red            1                   0
  #    Orange         1                   1
  #    Yellow         1                   2
  #    Green          1                   3
  #    Purple         1                   5
  #    Pink           1                   6
  #    Blue           1                   deleted
  #    Graphite       6                   -1
  - domain: NSGlobalDomain
    name: AppleAccentColor
    value: 3
    resets: Dock
  - domain: NSGlobalDomain
    name: AppleAquaColorVariant
    value: 1
    resets: Dock

  # System Preferences > General > Highlight color
  # Color    AppleHighlightColor
  # Red      "1.000000 0.733333 0.721569 Red"
  # Orange   "1.000000 0.874510 0.701961 Orange"
  # Yellow   "1.000000 0.937255 0.690196 Yellow"
  # Green    "0.752941 0.964706 0.678431 Green"
  # Purple   "0.968627 0.831373 1.000000 Purple"
  # Pink     "1.000000 0.749020 0.823529 Pink"
  # Blue     deleted
  # Graphite "0.847059 0.847059 0.862745 Graphite"
  - domain: NSGlobalDomain
    name: AppleHighlightColor
    value: "0.752941 0.964706 0.678431 Green"
    resets: Dock

  - domain: NSGlobalDomain
    name: AppleReduceDesktopTinting
    value: true

  # Increase window resize speed for Cocoa applications
  - domain: NSGlobalDomain
    name: NSWindowResizeTime
    value: 0.001

  # Expand save panel by default
  - domain: NSGlobalDomain
    name: NSNavPanelExpandedStateForSaveMode
    value: true
  - domain: NSGlobalDomain
    name: NSNavPanelExpandedStateForSaveMode2
    value: true

  # Disable swipe between pages gestures
  - domain: NSGlobalDomain
    name: AppleEnableSwipeNavigateWithScrolls
    value: false

  # Save to disk (not to iCloud) by default
  - domain: NSGlobalDomain
    name: NSDocumentSaveNewDocumentsToCloud
    value: false

  # Disable the "Are you sure you want to open this application?" dialog
  - domain: com.apple.LaunchServices
    name: LSQuarantine
    value: false

  # Disable automatic termination of inactive apps
  - domain: NSGlobalDomain
    name: NSDisableAutomaticTermination
    value: true

  # Disable animations when opening and closing windows.
  - domain: NSGlobalDomain
    name: NSAutomaticWindowAnimationsEnabled
    value: false

  # Set sidebar icon size to medium
  - domain: NSGlobalDomain
    name: NSTableViewDefaultSizeMode
    value: 2

  # Always show scrollbars
  - domain: NSGlobalDomain
    name: AppleShowScrollBars
    value: Always

  # Disable the over-the-top focus ring animation
  - domain: NSGlobalDomain
    name: NSUseAnimatedFocusRing
    value: false

  # Adjust toolbar title rollover delay
  - domain: NSGlobalDomain
    name: NSToolbarTitleViewRolloverDelay
    value: 0

  # Disable Resume system-wide
  - domain: com.apple.systempreferences
    name: NSQuitAlwaysKeepsWindows
    value: false

  # Context menu item for showing the Web Inspector in web views
  - domain: NSGlobalDomain
    name: WebKitDeveloperExtras
    value: true

  # Elastic (rubber band) over-scrolling
  - domain: NSGlobalDomain
    name: NSScrollViewRubberbanding
    value: false

  # Reopen windows when logging back in
  - domain: com.apple.loginwindow
    name: TALLogoutSavesState
    value: false

  # Show Input menu in menu bar
  - domain: com.apple.TextInputMenu
    name: visible
    value: false

  # Show Percent on Battery
  - domain: com.apple.menuextra.battery
    name: ShowPercent
    value: "YES"
    resets: SystemUIServer

  - domain: com.apple.systemuiserver
    name: menuExtras
    value:
      - "/System/Library/CoreServices/Menu Extras/Volume.menu"
      - "/System/Library/CoreServices/Menu Extras/Clock.menu"
      - "/System/Library/CoreServices/Menu Extras/Battery.menu"
      - "/System/Library/CoreServices/Menu Extras/AirPort.menu"
      - "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
    resets: SystemUIServer

  # NOTE: disables auto switching between desktop (mostly). Which means the random switches macos likes to do will stop, but also means intentional switching to focus an app may not always work. Plus there are some more subtle bugs with this that can be annoying at times.
  - domain: com.apple.dock
    name: workspaces-auto-swoosh
    value: false
    resets: Dock

  # % Bluetooth

  # Increase sound quality for Bluetooth headphones/headsets
  - domain: com.apple.BluetoothAudioAgent
    name: "Apple Bitpool Min (editable)"
    value: 40
    resets: coreaudiod

  # % Keyboard and input

  # Enable full keyboard access for all controls (Tab between all ui elements)
  - domain: NSGlobalDomain
    name: AppleKeyboardUIMode
    value: 3

  # System Preferences > Keyboard > Keyboard > Use all F1, F2, etc. keys as standard function keys
  - domain: NSGlobalDomain
    name: com.apple.keyboard.fnState
    value: true

  # System Preferences > Keyboard > Text > Add period with double-space
  - domain: NSGlobalDomain
    name: NSAutomaticPeriodSubstitutionEnabled
    value: false

  # System Preferences > Trackpad > Look up & data detectors: Off
  - domain: NSGlobalDomain
    name: com.apple.trackpad.forceClick
    value: false

  # Disable press-and-hold for keys in favor of key repeat
  - domain: NSGlobalDomain
    name: ApplePressAndHoldEnabled
    value: false

  # Set a fast keyboard repeat rate
  # NOTE: values based on my linux settings: xset r rate 400 20
  # InitialKeyRepeat: 1 = 15ms
  # (400/15) = 26.666666666666668 ~ 27
  # KeyRepeat: 1 = 15ms
  # (20/15) = 1.3333333333333333 ~ 1
  - domain: NSGlobalDomain
    name: KeyRepeat
    value: 1
  - domain: NSGlobalDomain
    name: InitialKeyRepeat
    value: 27

  # % Screen

  # Enable subpixel font rendering on non-Apple LCDs
  - domain: NSGlobalDomain
    name: AppleFontSmoothing
    value: 1

  # % Finder

  # Disable desktop icons
  - domain: com.apple.finder
    name: CreateDesktop
    value: false
    resets: Finder

  # Save state of last tab
  - domain: com.apple.finder
    name: BackupTabState
    value: true
    resets: Finder

  # Allow custom default locations for new windows
  - domain: com.apple.finder
    name: NewWindowTarget
    value: PfLo
    resets: Finder

  # New windows open in home directory
  - domain: com.apple.finder
    name: NewWindowTargetPath
    value: file://{{ home }}
    resets: Finder

  # Folders are listed first in any Finder window.
  - domain: com.apple.finder
    name: _FXSortFoldersFirst
    value: true
    resets: Finder

  # Finder: show all filename extensions (also in file save dialogs)
  - domain: NSGlobalDomain
    name: AppleShowAllExtensions
    value: true
    resets: Finder

  # Finder: show path bar
  - domain: com.apple.finder
    name: ShowPathbar
    value: true
    resets: Finder

  # Finder: allow text selection in Quick Look
  - domain: com.apple.finder
    name: QLEnableTextSelection
    value: true
    resets: Finder

  # Display full POSIX path as Finder window title
  - domain: com.apple.finder
    name: _FXShowPosixPathInTitle
    value: true
    resets: Finder

  # When performing a search, search the current folder by default
  - domain: com.apple.finder
    name: FXDefaultSearchScope
    value: "SCcf"
    resets: Finder

  # Disable the warning when changing a file extension
  - domain: com.apple.finder
    name: FXEnableExtensionChangeWarning
    value: false
    resets: Finder

  # Enable spring loading for directories
  - domain: NSGlobalDomain
    name: com.apple.springing.enabled
    value: true
    resets: Finder

  # Remove the spring loading delay for directories
  - domain: NSGlobalDomain
    name: com.apple.springing.delay
    value: 0
    resets: Finder

  # Avoid creating .DS_Store files on network volumes
  - domain: com.apple.desktopservices
    name: DSDontWriteNetworkStores
    value: true
    resets: Finder

  # Avoid creating .DS_Store files on usb volumes
  - domain: com.apple.desktopservices
    name: DSDontWriteUSBStores
    value: true
    resets: Finder

  # Automatically open a new Finder window when a volume is mounted
  - domain: com.apple.frameworks.diskimages
    name: auto-open-ro-root
    value: true
    resets: Finder
  - domain: com.apple.frameworks.diskimages
    name: auto-open-rw-root
    value: true
    resets: Finder
  - domain: com.apple.finder
    name: OpenWindowForNewRemovableDisk
    value: true
    resets: Finder

  # Enable AirDrop over Ethernet and on unsupported Macs running Lion
  - domain: com.apple.NetworkBrowser
    name: BrowseAllInterfaces
    value: true
    resets: Finder

  # Disable animation when opening the Info window in Finder (cmdâŒ˜ + i).
  - domain: com.apple.finder
    name: DisableAllAnimations
    value: true
    resets: Finder

  # Disable animations when opening a Quick Look window.
  - domain: NSGlobalDomain
    name: QLPanelAnimationDuration
    value: 0
    resets: Finder

  # Hide tags
  - domain: com.apple.finder
    name: ShowRecentTags
    value: false
    resets: Finder

  - domain: com.apple.finder
    name: FXInfoPanesExpanded
    value:
      Comments: false
      General: true
      MetaData: false
      Name: false
      OpenWith: true
      Preview: false
      Privileges: true
    resets: Finder

  # Disable: Automatically rearrange Spaces based on most recent use
  - domain: com.apple.dock
    name: mru-spaces
    value: false
    resets: Dock

  # Speed up Mission Control animations
  - domain: com.apple.dock
    name: expose-animation-duration
    value: 0.1
    resets: Dock

  # Make Dock icons of hidden applications translucent
  - domain: com.apple.dock
    name: showhidden
    value: true
    resets: Dock

  # Don't show recent applications in Dock
  - domain: com.apple.dock
    name: show-recents
    value: false
    resets: Dock

  # Disable the Launchpad gesture (pinch with thumb and three fingers)
  - domain: com.apple.dock
    name: showLaunchpadGestureEnabled
    value: false
    resets: Dock

  # Set icon size
  - domain: com.apple.dock
    name: tilesize
    value: 10
    resets: Dock

  # position left
  - domain: com.apple.Dock
    name: orientation
    value: left
    resets: Dock

  # lock size
  - domain: com.apple.Dock
    name: size-immutable
    value: true
    resets: Dock

  # Dock: Prefer tabs when opening documents: always, fullscreen, manual
  - domain: NSGlobalDomain
    name: AppleWindowTabbingMode
    value: always
    resets: Dock

  # Disable animations when you open an application from the Dock.
  - domain: com.apple.dock
    name: launchanim
    value: false
    resets: Dock

  - domain: com.apple.dock
    name: autohide
    value: true
    resets: Dock

  - domain: com.apple.dock
    name: autohide-delay
    value: 0
    resets: Dock

  - domain: com.apple.dock
    name: autohide-time-modifier
    value: 0
    resets: Dock

  # % Terminal

  # Preferences... > General > New tabs open with: Default Profile
  - domain: com.apple.terminal
    name: NewTabSettingsBehavior
    value: true

  # Preferences... > General > New tabs open with: Default Working Directory
  - domain: com.apple.terminal
    name: NewTabWorkingDirectoryBehavior
    value: true

  # Preferences... > General > New windows open with: Default Profile
  - domain: com.apple.terminal
    name: NewWindowSettingsBehavior
    value: true

  # Preferences... > General > New windows open with: Default Working Directory
  - domain: com.apple.terminal
    name: NewWindowWorkingDirectoryBehavior
    value: true

  # Only use UTF-8 in Terminal.app
  - domain: com.apple.terminal
    name: StringEncodings
    value:
      - 4

  # Enable Secure Keyboard Entry in Terminal.app
  # See: https://security.stackexchange.com/a/47786/8918
  - domain: com.apple.terminal
    name: SecureKeyboardEntry
    # NOTE: changed to false for skhd
    value: false

  # Disable the annoying line marks
  - domain: com.apple.Terminal
    name: ShowLineMarks
    value: false

  # % Activity Monitor

  # Show the main window when launching Activity Monitor
  - domain: com.apple.ActivityMonitor
    name: OpenMainWindow
    value: true
    resets: Activity Monitor

  # Show all processes in Activity Monitor
  - domain: com.apple.ActivityMonitor
    name: ShowCategory
    value: 100
    resets: Activity Monitor

  # Sort Activity Monitor results by CPU usage
  - domain: com.apple.ActivityMonitor
    name: SortColumn
    value: CPUUsage
    resets: Activity Monitor
  - domain: com.apple.ActivityMonitor
    name: SortDirection
    value: 0
    resets: Activity Monitor

  # % TextEdit

  # Use plain text mode for new TextEdit documents
  - domain: com.apple.TextEdit
    name: RichText
    value: false

  # Open and save files as UTF-8 in TextEdit
  - domain: com.apple.TextEdit
    name: PlainTextEncoding
    value: 4
  - domain: com.apple.TextEdit
    name: PlainTextEncodingForWrite
    value: 4

  # % Disk Utility

  # Enable the debug menu in Disk Utility
  - domain: com.apple.DiskUtility
    name: DUDebugMenuEnabled
    value: true
  - domain: com.apple.DiskUtility
    name: advanced-image-options
    value: true

  # % Photos

  # Prevent Photos from opening automatically when devices are plugged in
  - domain: com.apple.ImageCapture
    name: disableHotPlug
    value: true

  # % Google Chrome

  # Disable the all too sensitive backswipe on trackpads
  - domain: com.google.Chrome
    name: AppleEnableSwipeNavigateWithScrolls
    value: false

  # % Safari

  # Prevent Safari from opening 'safe' files automatically after downloading
  # - domain: com.apple.Safari
  #   name: AutoOpenSafeDownloads
  #   value: false

  # % Screenshots

  # Save screenshots to ~/Screenshots/{hostname}

  - domain: com.apple.screencapture
    name: location
    value: "{{ home }}/Screenshots/{{ machine }}"
    resets: SystemUIServer

  # Include date in screenshot filenames
  - domain: com.apple.screencapture
    name: include-date
    value: true
    resets: SystemUIServer

---
when:
  - machine != "work-paige"
  - os == "macos"

sudoers:
  mode: passwordless
  defaults: |
    # Don't keep HOME (that's super obnoxious)
    Defaults env_keep -= "HOME"
    # But do keep PATH so we can run our commands as root
    Defaults exempt_group = {{ user }}

packages:
  - homebrew/cask/google-chrome
  - homebrew/cask/1password

macos.pmset:
  battery:
    displaysleep: 15
    sleep: 15
  ac:
    displaysleep: 0
    sleep: 0

macos.defaults:
  # % System updates

  # Enable the automatic update check
  - domain: com.apple.SoftwareUpdate
    name: AutomaticCheckEnabled
    value: true

  # Check for software updates daily, not just once per week
  - domain: com.apple.SoftwareUpdate
    name: ScheduleFrequency
    value: 1

  # Download newly available updates in background
  - domain: com.apple.SoftwareUpdate
    name: AutomaticDownload
    value: true

  # Install System data files & security updates
  - domain: com.apple.SoftwareUpdate
    name: CriticalUpdateInstall
    value: true

  # Automatically download apps purchased on other Macs
  - domain: com.apple.SoftwareUpdate
    name: ConfigDataInstall
    value: false

  # Turn on app auto-update
  - domain: com.apple.commerce
    name: AutoUpdate
    value: false

  # Allow the App Store to reboot machine on macOS updates
  - domain: com.apple.commerce
    name: AutoUpdateRestartRequired
    value: false

# I'M WORKIN HERE
---
when:
  - machine == "work-paige"
  - os == "macos"

macos.pmset:
  all:
    displaysleep: 15
    sleep: 15

sudoers:
  defaults: |
    Defaults timestamp_timeout=15
