[settings]
# missing_runtime_behavior = "autoinstall"
trusted_config_paths = ["~/Projects", "~/Work"]
legacy_version_file = true
status.missing_tools = "always"

[tools]
neovim = "nightly"
node = "latest"
prettier = "3.8.1"
rust = "stable"
